from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.start, name="start"),
    url(r'^home', views.home, name='home'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^bio', views.bio, name='bio'),
    url(r'^cs', views.cs, name='cs'),
    url(r'^sis', views.sis, name='sis'),
    url(r'^facbio', views.facbio, name='facbio'),
    url(r'^fyearbio', views.fyearbio, name='fyearbio'),
    url(r'^faccs', views.faccs, name='faccs'),
    url(r'^fyearcs', views.fyearcs, name='fyearcs'),
    url(r'^facsis', views.facsis, name='facsis'),
    url(r'^fyearsis', views.fyearsis, name='fyearsis'),
    url(r'^coursesis', views.coursesis, name='coursesis'),
    url(r'^coursebio', views.coursebio, name='coursebio'),
    url(r'^coursecs', views.coursecs, name='coursecs'),
    url(r'^getsisCourseID', views.getsisCourseID, name='getsisCourseID'),
    url(r'^getbioCourseID', views.getbioCourseID, name='getbioCourseID'),
    url(r'^getcsCourseID', views.getcsCourseID, name='getcsCourseID'),
    url(r'^getsisCourseClass', views.getsisCourseClass, name='getsisCourseClass'),
    url(r'^getbioCourseClass', views.getbioCourseClass, name="getbioCourseClass"),
    url(r'^getcsCourseClass', views.getcsCourseClass, name="getcsCourseClass"),
    url(r'^getsisCID', views.getsisCID, name='getsisCID'),
    url(r'^getbioCID', views.getbioCID, name='getbioCID'),
    url(r'^getcsCID', views.getcsCID, name='getcsCID'),
    url(r'^office_sis_details', views.office_sis_details, name='office_sis_details'),
    url(r'^office_bio_details', views.office_bio_details, name='office_bio_details'),
    url(r'^officecsdetails', views.officecsdetails, name='officecsdetails'),
    url(r'^year_sis_details', views.year_sis_details, name='year_sis_details'),
    url(r'^year_bio_details', views.year_bio_details, name='year_bio_details'),
    url(r'^year_cs_details', views.year_cs_details, name='year_cs_details'),
    url(r'^welcome', views.welcome, name='welcome'),
]
